In [2]:
import numpy as np

In [3]:
mylist = [1,2,3,4,5]

In [4]:
type(mylist)

list

In [6]:
myarray = np.array(mylist)

In [7]:
type(myarray)

numpy.ndarray

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.random.seed(42)
arr = np.random.randint(0,100,10)

In [22]:
arr

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [24]:
arr2 = np.random.randint(0,100,10)
arr2.max()

91

In [23]:
arr.max()

92

In [25]:
arr.argmax()

1

In [26]:
arr.mean()

62.4

In [27]:
arr.shape

(10,)

In [28]:
arr

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [33]:
arr.reshape((2,5))

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74]])

In [34]:
matrix = np.arange(0,100).reshape(10,10)

In [35]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
row = 0
col = 1
matrix[row, col]

1

In [37]:
row = 5
col = 6
matrix[row, col]

56

In [39]:
matrix[4,6]

46

#### Return all values in the column eg column 5 [:,5]

In [48]:
matrix[:,5].reshape((10,1))

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

#### Return all values in a row eg row 2 [2,:]

In [53]:
matrix[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### Slicing parts of the matrix

In [57]:
matrix[0:3, 0:5] = 0

In [58]:
matrix

array([[ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])